# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nUTmNjrw0XGThj2VUmhWeokUgLP5TQpW
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

from tensorflow.keras.datasets import mnist

(X_train,y_train),(X_test,y_test) = mnist.load_data()

X_train = X_train.reshape((60000,784))
X_test = X_test.reshape((10000,784))

plt.imshow(X_train[58].reshape((28,28)),'gray')
print(y_train[58])



"""[DecisionTree sklearn documentation](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html)"""

clf = DecisionTreeClassifier(criterion='entropy',
                             max_depth=15,
                             min_samples_leaf=3,
                             min_weight_fraction_leaf=0.0001)
clf.fit(X_train,y_train)

prediction = clf.predict(X_test)

accuracy_score(prediction,y_test)

confusion_matrix(prediction,y_test)

