# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10UXF1R_iCRASlwLs6xLtXVsillIGwiYO
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn import svm,metrics

from tensorflow.keras.datasets import mnist

(X_train,y_train),(X_test,y_test) = mnist.load_data()

X_train[X_train>0] = 1
X_test[X_test>0] = 1

data_train = X_train[:10000].reshape((10000,784))
label_train = y_train[:10000]

data_test = X_test[:2000].reshape((2000,784))
label_test = y_test[:2000]

classifier = svm.SVC(C=500,kernel='rbf',gamma=0.01,cache_size=8000,probability=False)

data_train.shape

classifier.fit(data_train,label_train)

predicted = classifier.predict(data_test)

print("Classification report: {}".format(metrics.classification_report(label_test,predicted)))

print("Confusion matrix:\n{}".format(metrics.confusion_matrix(label_test,predicted)))

metrics.accuracy_score(label_test,predicted)

